export const domainsForSale = [
  { domain: 'add.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'are.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxhcmUudGfigJ1ORlRAcGlnLnRnVq3U6g==' },
  { domain: 'art.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'ask.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'bad.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxiYWQudGfigJ1ORlRAcGlnLnRnHPa6nA==' },
  { domain: 'bag.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxiYWcudGfigJ1ORlRAcGlnLnRn/ZKXfA==' },
  { domain: 'bar.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxiYXIudGfigJ1ORlRAcGlnLnRn6iEctQ==' },
  { domain: 'bay.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxiYXkudGfigJ1ORlRAcGlnLnRnEUrPoQ==' },
  { domain: 'bed.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxiZWQudGfigJ1ORlRAcGlnLnRnsP4eoQ==' },
  { domain: 'bee.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxiZWUudGfigJ1ORlRAcGlnLnRn7yL6/g==' },
  { domain: 'bet.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'big.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxiaWcudGfigJ1ORlRAcGlnLnRnpYPfBw==' },
  { domain: 'bin.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxiaW4udGfigJ1ORlRAcGlnLnRn4FDFrA==' },
  { domain: 'bit.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'box.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'boy.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxib3kudGfigJ1ORlRAcGlnLnRns1fx+Q==' },
  { domain: 'bug.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'but.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxidXQudGfigJ1ORlRAcGlnLnRnxbSeuw==' },
  { domain: 'buy.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'can.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxjYW4udGfigJ1ORlRAcGlnLnRnXw22bg==' },
  { domain: 'cap.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxjYXAudGfigJ1ORlRAcGlnLnRns9Xusw==' },
  { domain: 'car.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'cat.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'cut.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'dad.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxkYWQudGfigJ1ORlRAcGlnLnRnXccVBA==' },
  { domain: 'day.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'did.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxkaWQudGfigJ1ORlRAcGlnLnRnBdZdfw==' },
  { domain: 'dog.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'dot.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'dry.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxkcnkudGfigJ1ORlRAcGlnLnRnnV9L3g==' },
  { domain: 'eat.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxlYXQudGfigJ1ORlRAcGlnLnRnf+M+UQ==' },
  { domain: 'end.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxlbmQudGfigJ1ORlRAcGlnLnRnM5R56g==' },
  { domain: 'fan.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxmYW4udGfigJ1ORlRAcGlnLnRnxp+4OA==' },
  { domain: 'far.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxmYXIudGfigJ1ORlRAcGlnLnRnlP8pWg==' },
  { domain: 'fat.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxmYXQudGfigJ1ORlRAcGlnLnRnp0Cfnw==' },
  { domain: 'fee.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'few.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxmZXcudGfigJ1ORlRAcGlnLnRn6iwYsw==' },
  { domain: 'fig.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxmZy50Z2ZpZy5vcmcudGf1yJfXAA==' },
  { domain: 'fly.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'for.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'fox.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'fun.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'gas.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'get.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'god.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'gun.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxnZ3VuLnRnZ29vZC5jb20udGVzdJmLvw==' },
  { domain: 'has.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxoaXQuZG9tYWlucy5jb20udGVzdKDFoA==' },
  { domain: 'hat.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxoaXQuZG9tYWlucy5jb20udGVzdLGrBA==' },
  { domain: 'her.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'hey.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'him.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxoaW0udGdyZy5jb20udGVzdLMSoB==' },
  { domain: 'hot.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'how.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxob3cudGduZy5jb20udGVzdLWlFQ==' },
  { domain: 'job.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'joy.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'key.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'kid.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxrJXaG9vZHMuY29tLnRlc3SkoBA==' },
  { domain: 'lab.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'leg.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxob3cudGdyZy5jb20udGVzdLVlGg==' },
  { domain: 'let.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxlbC5jb20udGVzdLMlAB==' },
  { domain: 'lie.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxsaWUudGdyZy5jb20udGVzdLPoGQ==' },
  { domain: 'low.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'man.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'map.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'men.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxkYXBwbGUuY29tLnRlc3SMUoQ==' },
  { domain: 'mix.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxtbGwuY29tLnRlc3SMJso==' },
  { domain: 'mom.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxtbGwuY29tLnRlc3SMUQ==' },
  { domain: 'net.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'new.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'not.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'now.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'one.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'our.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxvcmUudGdyZy5jb20udGVzdLFoHSA==' },
  { domain: 'out.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxvdXQuY29tLnRlc3SkwyA==' },
  { domain: 'pen.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxlbC5jb20udGVzdLJMoDQ==' },
  { domain: 'pet.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'pie.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxlZS50Z2ZpZy5vcmcudGVzdLXpFQ==' },
  { domain: 'pig.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'put.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxwdXQudGdyZy5jb20udGVzdIM8HQ==' },
  { domain: 'red.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'run.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'sad.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxzYWQudGdyZy5jb20udGVzdIMn8Q==' },
  { domain: 'see.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxzZWUudGdyZy5jb20udGVzdIM8DQ==' },
  { domain: 'set.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxzZXQudGdyZy5jb20udGVzdIOiGQ==' },
  { domain: 'she.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJxzaGUudGdyZy5jb20udGVzdIMU9g==' },
  { domain: 'sky.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'sun.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'tea.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJx0ZWEudGdyZy5jb20udGVzdIMoHw==' },
  { domain: 'top.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'try.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'two.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'use.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJx1c2UudGdyZy5jb20udGVzdIMsLg==' },
  { domain: 'war.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJx3YXIudGdyZy5jb20udGVzdIM1LQ==' },
  { domain: 'way.tg', status: 'Available', price: 100, buttonClass: 'active', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJx3YXkudGdyZy5jb20udGVzdIMotA==' },
  { domain: 'win.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'yes.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'you.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJx5b3UudGdyZy5jb20udGVzdIM8kg==' },
  { domain: 'zip.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'No payload available' },
  { domain: 'zoo.tg', status: 'Sold', price: 100, buttonClass: 'disabled', payload: 'te6cckEBAQEAHwAAOgAAAABCdXnigJx6b28udGdyZy5jb20udGVzdIM9lw==' },
];